/**
 * The Rust SDK generator.
 *
 * Emits a namespaced facade over the clients `protoc-gen-connect-rust` already
 * generates. Nothing here touches the wire: the generated clients do the
 * calling, and this decides only what the methods are named and how they are
 * grouped.
 *
 * The shape follows `async-openai`: one client owning the transport, and
 * borrowed group structs reached through accessors, so `client.workspaces()`
 * costs nothing and borrows rather than clones.
 */

import type { DescFile, DescMethod } from "@bufbuild/protobuf";
import type { GeneratedFile, Schema } from "@bufbuild/protoplugin";
import { getComments } from "@bufbuild/protoplugin";

import { words } from "./names.js";
import { findCollision, planNamespaces, type PlannedNamespace } from "./plan.js";

/** Where the messages and clients this SDK delegates to were generated. */
export interface RustOptions {
  /** Rust path of the `protoc-gen-connect-rust` output, as `crate::generated::service`. */
  readonly servicePath: string;
  /** Rust path of the `protoc-gen-buffa` output, as `crate::generated::messages`. */
  readonly messagePath: string;
  /**
   * Rust paths for proto packages generated elsewhere, by proto package name.
   *
   * Mirrors the `extern_path` option the message and service generators take,
   * and is needed for the same reason: a request or response may be a
   * well-known type, which lives in `buffa_types` rather than beside the
   * package's own messages.
   */
  readonly externPaths: ReadonlyMap<string, string>;
}

/** Generates one `sdk.rs` per proto package. */
export function generateRust(schema: Schema<RustOptions>): void {
  for (const [pkg, files] of groupByPackage(schema.files)) {
    const services = files.flatMap((file) => [...file.services]);
    if (services.length === 0) {
      continue;
    }
    const namespaces = planNamespaces(services);
    for (const namespace of namespaces) {
      const collision = findCollision(namespace);
      if (collision !== undefined) {
        throw new Error(
          `Two methods in "${namespace.name}" are both named "${collision}". ` +
            `Set option (connectsdk.v1.method) on one of them.`,
        );
      }
    }
    generateFile(schema.generateFile(`${pkg}.sdk.rs`), files[0]!, namespaces, schema.options);
  }
}

function groupByPackage(files: readonly DescFile[]): Map<string, DescFile[]> {
  const packages = new Map<string, DescFile[]>();
  for (const file of files) {
    const group = packages.get(file.proto.package) ?? [];
    group.push(file);
    packages.set(file.proto.package, group);
  }
  return packages;
}

function generateFile(
  f: GeneratedFile,
  file: DescFile,
  namespaces: readonly PlannedNamespace[],
  options: RustOptions,
): void {
  const pkg = file.proto.package;
  f.print("// @generated by protoc-gen-connect-sdk. DO NOT EDIT.");
  f.print();
  // Outer comments rather than `//!`, so the file can be pulled in with
  // `include!` — an inner doc comment is only legal at the top of a module's
  // own file, and `include!` splices this into the middle of one.
  f.print("// An idiomatic client for the `", pkg, "` API.");
  f.print("//");
  f.print("// Methods are grouped by the resource they act on, so a call reads as");
  f.print(
    "// `client.",
    namespaces[0]?.name ?? "resources",
    "().",
    firstMethod(namespaces),
    "(request)`.",
  );
  f.print();

  const services = [...new Set(namespaces.flatMap((namespace) => [...namespace.services]))];

  f.print("/// A client for the `", pkg, "` API.");
  f.print("///");
  f.print("/// Generic over the transport, so the same client serves an HTTP connection,");
  f.print("/// an in-process service, or a test double.");
  f.print("#[derive(Clone)]");
  f.print("pub struct ", clientName(pkg), "<T> {");
  for (const service of services) {
    f.print(
      "    ",
      fieldName(service.name),
      ": ",
      options.servicePath,
      "::",
      service.name,
      "Client<T>,",
    );
  }
  // The generated clients keep their transport and configuration private, so
  // the byot methods — which call the transport directly with types the
  // schema does not name — need their own copy to reach.
  f.print('    #[cfg(feature = "byot")]');
  f.print("    transport: T,");
  f.print('    #[cfg(feature = "byot")]');
  f.print("    config: ::connectrpc::client::ClientConfig,");
  f.print("}");
  f.print();

  f.print("impl<T> ", clientName(pkg), "<T>");
  f.print("where");
  f.print("    T: ::connectrpc::client::ClientTransport,");
  f.print("    <T::ResponseBody as ::connectrpc::http_body::Body>::Error: ::std::fmt::Display,");
  f.print("{");
  f.print("    /// Creates a client over one transport and configuration.");
  f.print("    pub fn new(transport: T, config: ::connectrpc::client::ClientConfig) -> Self");
  f.print("    where");
  f.print("        T: Clone,");
  f.print("    {");
  f.print("        Self {");
  for (const service of services) {
    f.print(
      "            ",
      fieldName(service.name),
      ": ",
      options.servicePath,
      "::",
      service.name,
      "Client::new(transport.clone(), config.clone()),",
    );
  }
  f.print('            #[cfg(feature = "byot")]');
  f.print("            transport: transport.clone(),");
  f.print('            #[cfg(feature = "byot")]');
  f.print("            config: config.clone(),");
  f.print("        }");
  f.print("    }");
  for (const namespace of namespaces) {
    f.print();
    f.print("    /// ", namespaceDoc(namespace));
    f.print(
      "    pub fn ",
      snake(namespace.name),
      "(&self) -> ",
      groupName(namespace.name),
      "<'_, T> {",
    );
    f.print("        ", groupName(namespace.name), " { client: self }");
    f.print("    }");
  }
  f.print("}");

  for (const namespace of namespaces) {
    f.print();
    f.print("/// ", namespaceDoc(namespace));
    f.print("pub struct ", groupName(namespace.name), "<'c, T> {");
    f.print("    client: &'c ", clientName(pkg), "<T>,");
    f.print("}");
    f.print();
    f.print("impl<T> ", groupName(namespace.name), "<'_, T>");
    f.print("where");
    f.print("    T: ::connectrpc::client::ClientTransport,");
    f.print("    <T::ResponseBody as ::connectrpc::http_body::Body>::Error: ::std::fmt::Display,");
    f.print("{");
    for (const [index, method] of namespace.methods.entries()) {
      if (index > 0) {
        f.print();
      }
      printMethod(f, method.name, method.desc, options);
    }
    f.print("}");
  }
}

/**
 * One method, delegating to the generated client.
 *
 * Unary calls return the response message rather than the transport's
 * `UnaryResponse`, since headers and trailers are a detail of the hop and a
 * caller wanting them can reach the generated client directly. Streaming
 * calls return the stream itself, which is already the useful shape.
 */
function printMethod(f: GeneratedFile, name: string, desc: DescMethod, options: RustOptions): void {
  const rustName = snake(name);
  const delegate = snake(desc.name);
  const request = messagePath(desc.input, options);
  for (const line of docLines(desc)) {
    f.print("    /// ", line);
  }
  if (desc.methodKind === "server_streaming") {
    f.print("    pub async fn ", rustName, "(");
    f.print("        &self,");
    f.print("        request: ", request, ",");
    f.print("    ) -> ::std::result::Result<");
    f.print(
      "        ::connectrpc::client::ServerStream<T::ResponseBody, ",
      viewPath(desc.output, options),
      ">,",
    );
    f.print("        ::connectrpc::ConnectError,");
    f.print("    > {");
    f.print("        self.client.", fieldName(desc.parent.name), ".", delegate, "(request).await");
    f.print("    }");
    printByot(f, rustName, desc, options, "server_streaming");
    return;
  }
  // A client-streaming call sends many requests and receives one response,
  // so it takes an iterator. The generated client already has this shape;
  // matching it is what keeps the delegation a single call.
  if (desc.methodKind === "client_streaming") {
    f.print("    pub async fn ", rustName, "(");
    f.print("        &self,");
    f.print("        requests: impl IntoIterator<Item = ", request, ">,");
    f.print(
      "    ) -> ::std::result::Result<",
      messagePath(desc.output, options),
      ", ::connectrpc::ConnectError> {",
    );
    f.print("        Ok(self");
    f.print("            .client");
    f.print("            .", fieldName(desc.parent.name));
    f.print("            .", delegate, "(requests)");
    f.print("            .await?");
    f.print("            .into_owned())");
    f.print("    }");
    printByot(f, rustName, desc, options, "client_streaming");
    return;
  }
  f.print("    pub async fn ", rustName, "(");
  f.print("        &self,");
  f.print("        request: ", request, ",");
  f.print(
    "    ) -> ::std::result::Result<",
    messagePath(desc.output, options),
    ", ::connectrpc::ConnectError> {",
  );
  f.print("        Ok(self");
  f.print("            .client");
  f.print("            .", fieldName(desc.parent.name));
  f.print("            .", delegate, "(request)");
  f.print("            .await?");
  f.print("            .into_owned())");
  f.print("    }");
  printByot(f, rustName, desc, options, "unary");
}

/**
 * The bring-your-own-types twin of one method.
 *
 * Generic over request and response so a caller can send and receive their
 * own types — a hand-rolled struct, or one carrying a field this schema does
 * not yet describe. The wire call is the same; only the types at the edges
 * change, which is why it delegates to the same generated client rather than
 * duplicating the call.
 *
 * Behind the `byot` feature, following `async-openai`, so the ordinary
 * signature stays the one that shows up in documentation.
 */
function printByot(
  f: GeneratedFile,
  rustName: string,
  desc: DescMethod,
  options: RustOptions,
  kind: "unary" | "server_streaming" | "client_streaming",
): void {
  f.print();
  f.print("    /// The [`", rustName, "`](Self::", rustName, ") call over caller-chosen types.");
  f.print('    #[cfg(feature = "byot")]');
  if (kind === "server_streaming") {
    f.print("    pub async fn ", rustName, "_byot<Req, RespView>(");
    f.print("        &self,");
    f.print("        request: Req,");
    f.print(
      "    ) -> ::std::result::Result<::connectrpc::client::ServerStream<T::ResponseBody, RespView>, ::connectrpc::ConnectError>",
    );
    f.print("    where");
    f.print("        Req: ::buffa::Message + ::connectrpc::JsonSerialize,");
    f.print("        RespView: ::buffa::view::MessageView<'static> + Send,");
    f.print("        RespView::Owned: ::buffa::Message + ::connectrpc::JsonDeserialize,");
    f.print("    {");
    f.print("        ::connectrpc::client::call_server_stream(");
  } else if (kind === "client_streaming") {
    f.print("    pub async fn ", rustName, "_byot<Req, RespView>(");
    f.print("        &self,");
    f.print("        requests: impl IntoIterator<Item = Req>,");
    f.print("    ) -> ::std::result::Result<RespView::Owned, ::connectrpc::ConnectError>");
    f.print("    where");
    f.print("        Req: ::buffa::Message + ::connectrpc::JsonSerialize,");
    f.print("        RespView: ::buffa::view::MessageView<'static> + Send,");
    f.print("        RespView::Owned: ::buffa::Message + ::connectrpc::JsonDeserialize,");
    f.print("    {");
    f.print("        ::connectrpc::client::call_client_stream::<_, _, RespView>(");
  } else {
    f.print("    pub async fn ", rustName, "_byot<Req, RespView>(");
    f.print("        &self,");
    f.print("        request: Req,");
    f.print("    ) -> ::std::result::Result<RespView::Owned, ::connectrpc::ConnectError>");
    f.print("    where");
    f.print("        Req: ::buffa::Message + ::connectrpc::JsonSerialize,");
    f.print("        RespView: ::buffa::view::MessageView<'static> + Send,");
    f.print("        RespView::Owned: ::buffa::Message + ::connectrpc::JsonDeserialize,");
    f.print("    {");
    f.print("        ::connectrpc::client::call_unary::<_, _, RespView>(");
  }
  f.print("            &self.client.transport,");
  f.print("            &self.client.config,");
  f.print("            ", options.servicePath, "::", serviceNameConst(desc.parent.name), ",");
  f.print("            ", quoted(desc.name), ",");
  f.print("            ", kind === "client_streaming" ? "requests," : "request,");
  f.print("            ::connectrpc::client::CallOptions::default(),");
  f.print("        )");
  if (kind === "server_streaming") {
    f.print("        .await");
  } else {
    f.print("        .await");
    f.print("        .map(::connectrpc::client::UnaryResponse::into_owned)");
  }
  f.print("    }");
}

/** The generated constant holding one service's fully-qualified name. */
function serviceNameConst(serviceName: string): string {
  return `${snake(serviceName).toUpperCase()}_SERVICE_NAME`;
}

function quoted(value: string): string {
  return JSON.stringify(value);
}

/**
 * The Rust path of one message.
 *
 * A message from another proto package was generated by another invocation,
 * so its path comes from `extern_path` rather than from this package's own
 * output. `google.protobuf.Empty` is the common case.
 */
function messagePath(desc: { typeName: string; name: string }, options: RustOptions): string {
  const root = rootFor(desc.typeName, options);
  return `${root}::${desc.name}`;
}

/** The zero-copy view type of one message, which streams are generic over. */
function viewPath(desc: { typeName: string; name: string }, options: RustOptions): string {
  const root = rootFor(desc.typeName, options);
  return `${root}::__buffa::view::${desc.name}View<'static>`;
}

/** The module a message's package generated into. */
function rootFor(typeName: string, options: RustOptions): string {
  const pkg = typeName.split(".").slice(0, -1).join(".");
  return options.externPaths.get(pkg) ?? options.messagePath;
}

/**
 * The schema's own comment for a method, as doc lines.
 *
 * Falls back to naming the RPC, so every generated method carries a doc
 * comment even where the schema left one out.
 */
function docLines(desc: DescMethod): string[] {
  const comment = (getComments(desc).leading ?? "")
    .split("\n")
    .map((line: string) => line.replace(/^ /v, ""))
    .join("\n")
    .trim();
  return comment === "" ? [`Calls \`${desc.name}\`.`] : comment.split("\n");
}

function namespaceDoc(namespace: PlannedNamespace): string {
  return `Methods of ${namespace.services.map((service) => `\`${service.typeName}\``).join(", ")}.`;
}

function firstMethod(namespaces: readonly PlannedNamespace[]): string {
  return snake(namespaces[0]?.methods[0]?.name ?? "get");
}

/** `sloper.desktop.v1` gives `SloperDesktopClient`, dropping the version. */
function clientName(pkg: string): string {
  const parts = pkg.split(".").filter((part) => !/^v\d+(?:[a-z]\w*)?$/v.test(part));
  return `${parts.map(pascalWord).join("")}Client`;
}

function groupName(namespace: string): string {
  return words(namespace).map(pascalWord).join("");
}

function fieldName(serviceName: string): string {
  return snake(serviceName);
}

function pascalWord(word: string): string {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

function snake(name: string): string {
  return words(name).join("_");
}
